function Card (q, s, btnTxt1, btnTxt2, btnTxt3, btnTxt4, path1, path2, path3, path4, xpos, ypos, zpos) {
	this.question = q;
	this.statement = s;
	this.btn1 = new Button(path1, btnTxt1);
	this.btn2 = new Button(path2, btnTxt2);
	this.btn3 = new Button(path3, btnTxt3);
	this.btn4 = new Button(path4, btnTxt4);
	this.incomingPaths = [];
	this.x = xpos;
	this.y = ypos;
	this.z = zpos;
}

Card.prototype.addIP = function addIP(cardID) {
	this.incomingPaths.push(cardID);
}

function Button (id, text) {
	this.pathID = id;
	this.text = text;
}

var endCard = "";
var endPath = null;
var btn3EndPath = -2;
var btn4EndPath = -2;

var questions = ["Do you think you actually need it?", "Does it cost about the amount you pay for rent?", "Don't buy it", "Where will the device be used?",
								 "How will it improve your life?", "Are you in shape?", "Do you know your daily calorie intake?", "Are you up before noon on the weekends?", "Buy It",
								 "Are you trying to look/feel good for an occasion?", "Don't buy it",
								 "To look good for someone else?", "What industry are you in?",
								 "Do you participate in operations?", "Don't buy it",
								 "Are you the second coming of Steve Jobs?", "Buy it",
								 "Are you Gordon Gecko?", "Does it involve children?",
								 "Are they yours?", "Do you care about their privacy?",
								 "Don't buy it", "Pill Pusher?",
								 "Under the table?", "Buy it",
								 "Don't buy it", "Does it involve illegal activity?",
								 "Over/under on jail time", "Buy it",
								 "Caretaker?", "Does it involve animals?",
								 "How does it improve the well-beings of the animals?", "Don't buy it",
								 "Don't buy it", "Buy it",
								 "Do you live in a safe neighborhood?", "Don't buy it",
								 "What will it help you with?", "Specific to one room?",
								 "Is it the bedroom?", "Your bedroom?",
								 "More than just you in the room?", "Will the device benefit them?",
								 "Buy it", "Will it annoy them?",
								 "Buy it", "Planning to share the same room with that person forever?",
								 "Does it rely heavily on Wifi?", "Do you have a backup security plan when wifi/internet goes down?",
								 "Is it a vicious pet?", "Buy it",
								 "Can it automatically learn to better improve ease and security?", "Do you trust the company not to sell your data?",
								 "How confident are you with a baseball bat?", "Do you like kickstarter campaigns that under-deliver?",
								 "Don't buy it", "Temperature related?",
								 "Do you have extreme weather in 2 of the 4 seasons?", "Do you have kids?",
								 "Buy it", "Can you only interact with this device via smartphone?",
								 "Does it rely on wifi?", "Is your interenet provider Comcast?",
								 "Don't buy it", "Are you in the \"tech scene\"?",
								 "Do you feel like Google Glass was a success?", "Buy it",
								 "Don't buy it", "Is it the bathroom?",
								 "Using it to monitor bathroom usage?", "Do you have lots of visitors?",
								 "Don't buy it", "Hair related?",
								 "Where?", "Are photos or metrics involved?",
								 "Don't buy it", "Toilet/shower related?",
								 "Will people think you're weird for using it?", "Buy it",
								 "Do you have to configure it with your smartphone", "Is it in the kitchen?",
								 "If the device malfunctions, will it stop you from eating food?", "Do you like food more than just for staying alive?",
								 "Don't buy it", "Cant it get you directly/indirectly to eat better food?",
								 "Buy it", "If it's not about food, why is it in the kitchen?",
								 "Is it the living room", " Does it improve the TV watching experience?",
								 "Buy it", "Can it's settings be accidentally tampered with by meddling guest?", 
								 "Would that mean you'll lose your DVR'd episodes of Big Bang Theory?", "Don't buy it",
								 "Contact us!"];
								 
var statements = ["", "", 
									"Too early in the IoT game unless you thought Google Glass was a good investment.", "",
									"", "",
									"", "",
									"You have the right mindset. This device should assist you well into better health", "", 
									"Your commitment to being in shape is not strong enough. This device won't save you", "",
									"", "",
									"Perhaps noticing where the bleeding is coming from is higher priority at the moment", "",
									"You are a confident & cocky person--being an early adopter is right up your alley", "",
									"", "",
									"", "That ain't grandma on the other end..",
									"", "",
									"Best be on top of what people are demanding so you can be sure to have the supplies",
									"Anything that  diverts your attention may be costly to the people you're responsible for", "",
									"", "Only way to be on-top in your line of work is to be one step ahead of the game",
									"", "",
									"", "Revaluate the way you think first before going deeper into the rabbit hole that is IoT",
									"Be sure about what you're doing before adding more complexity to your life", "\"YMMV\" should be the tagline of all IoT devices right now",
									"", "That guy down the block will hack it and teach your kids how to make an apple bong",
									"", "",
									"", "",
									"", "",
									"If it's good enough for the bedroom, it will be a good time for those in it", "",
									"Those on the bleeding edge of technology have no time for naysayers", "",
									"", "",
									"", "It's always good to have a workaround when the device stops functioning correctly",
									"", "",
									"", "",
									"Can't go down the IoT path without having your data stolen one way or another", "",
									"", "",
									"There's lots going on in life--temperature control should join the 21st century", "",
									"", "",
									"Your mileage will vary, but it will skew more towards the \"FUUUU\" side of things", "",
									"", "You seemed prepared for the situation, but don't get your hopes too high for the device",
									"At this point of the IoT era, let's not get too carried away with things too tangentially", "",
									"", "",
									"Your friends don't want you to know whether they're taking a shit or not", "",
									"", "",
									"Unfortunately photos of your body may make it's way to social networks", "",
									"", "Don't worry about what people think, they don't understand those of us on the cutting edge",
									"", "",
									"", "",
									"Can't go down the IoT path without having your data stolen one way or another", "",
									"Eat better to live long enough to enjoy IoT devices that will soon cater to humans like in the movie, \"Wall-E\"", "",
									"", "",
									"Any IoT device that makes consuming media on the TV better is worth the risk", "",
									"", "IoT devices that does not make consuming media in the living room better is not worth the price of admission",
									"Visit us at www.coshx.com!"];

var btnTxt2 = ["Probably not",
									 "No", "Restart",
									 "In the home", "All notifications. All the time",
									 "Define shape", "No, but carbs are bad", 
									 "What time is it now?", "Restart",
									 "Yes", "Restart",
									 "No, just me", "Other",
									 "No", "Restart",
									 "Yes, I don't take shit from no one", "Restart",
									 "I don't know who he is", "No",
									 "Pretty sure they're not", "Nah, I've already created LinkedIn profiles for them to get ahead in life",
									 "Restart", "Yes",
									 "\"No\"", "Restart",
									 "Restart", "\"No\"",
									 "I'll be out before my kid's born", "Restart",
									 "Yes", "Yes",
									 "Let's me see what they're doing from afar", "Restart",
									 "Restart", "Restart",
									 "Pretty good, mostly old people and college kids around", "Restart",
									 "Security", "Yes",
									 "No", "No",
									 "Yes", "Not sure",
									 "Restart", "Maybe",
									 "Restart", "Yes, they're the one",
									 "No", "No",
									 "It's name is Hannibal Lecter Jr.", "Restart",
									 "Yes", "I have nothing to hide",
									 "Barry Bonds on roids", "Just disappointed",
									 "Restart", "No",
									 "No", "No",
									 "Restart", "Multiple ways",
									 "No", "No",
									 "Restart", "No",
									 "Glassholes", "Restart",
									 "Restart", "No",
									 "No", "Yes",
									 "Restart", "Yes",
									 "Down south", "No",
									 "Restart", "No",
									 "Yes", "Restart",
									 "Yes", "No",
									 "No", "No",
									 "Restart", "Yes",
									 "Restart", "\* rhetorical questions \*",
									 "Yes", "No",
									 "Restart", "Yes",
									 "Like I said, it's not related to the TV", "Restart",
									 ""];

var btnTxt1 = ["I think so",
									 "Yes", endCard,
									 "On my potato sack of a body", "Health/Fitness related",
									 "In good shape", "Yes",
									 "Early bird gets the worm", "",
									 "No", endCard,
									 "Yes", "Health",
									 "Yes", endCard,
									 "No, but I like Helvetica", endCard,
									 "Yes, greed is good", "Yes",
									 "I think so", "Yes, I only snapchat their photos to grandma",
									 endCard, "No",
									 "No", endCard,
									 endCard, "No",
									 "I will not be able to pee standing up anymore", endCard,
									 "No", "No",
									 "Umm..", endCard,
									 endCard, endCard,
									 "I make sure my doors and windows are locked before sleeping", endCard,
									 "Utility", "Doesn't matter",
									 "Yes", "Yes",
									 "Room all to myself", "Yes",
									 endCard, "Nahhh",
									 endCard, "No", 
									 "Yes", "Yes",
									 "It'll lick them to death", endCard,
									 "No", "HAHAHAHA",
									 "..I have arms", "I get a refund",
									 endCard, "Yes",
									 "I melt and freeze in the same week", "I have hellspawn(s)",
									 endCard, "Yes",
									 "Yes", "No other options around",
									 endCard, "Yes",
									 "Great device", endCard,
									 endCard, "Yes",
									 "Yes", "No",
									 endCard, "No",
									 "Above the waist", "Yes",
									 endCard, "Yes",
									 "No", endCard,
									 "No", "Yes",
									 "Good chance--call it the hunger games", "Yes",
									 endCard, "No",
									 endCard, "",
									 "No", "I can now change the channel by farting",
									 endCard, "No",
									 "", endCard,
									 ""];

var btnTxt3 = ["",
									 "", endCard,
									 "", "",
									 "", "",
									 "", "",
									 "", endCard,
									 "", "Finance",
									 "", endCard,
									 "", endCard,
									 "", "",
									 "", "",
									 endCard, "",
									 "", endCard,
									 endCard, "",
									 "", endCard,
									 "", "",
									 "Let's me know when to give them food and shelter", endCard,
									 endCard, endCard,
									 "", endCard,
									 "", "",
									 "", "",
									 "", "",
									 endCard, "",
									 endCard, "",
									 "", "",
									 "", endCard,
									 "", "",
									 "", "",
									 endCard, "",
									 "", "",
									  endCard, "",
									 "", "",
									 endCard, "",
									 "", endCard,
									 endCard, "",
									 "", "",
									 endCard, "",
									 "", "",
									 endCard, "",
									 "", endCard,
									 "", "",
									 "", "",
									 endCard, "",
									 endCard, "",
									 "", "",
									 endCard, "",
									 "", endCard,
									 ""];

var btnTxt4 = ["",
									 "", endCard,
									 "", "",
									 "", "",
									 "", "",
									 "", endCard,
									 "", "Tech",
									 "", endCard,
									 "", endCard,
									 "", "",
									 "", "",
									 endCard, "",
									 "", endCard,
									 endCard, "",
									 "", endCard,
									 "", "",
									 "", endCard,
									 endCard, endCard,
									 "", endCard,
									 "", "",
									 "", "",
									 "", "",
									 endCard, "",
									 endCard, "",
									 "", "",
									 "", endCard,
									 "", "",
									 "", "",
									 endCard, "",
									 "", "",
									 endCard, "",
									 "", "",
									 endCard, "",
									 "", endCard,
									 endCard, "",
									 "", "",
									 endCard, "",
									 "", "",
									 endCard, "",
									 "", endCard,
									 "", "",
									 "", "",
									 endCard, "",
									 endCard, "",
									 "", "",
									 endCard, "",
									 "", endCard,
									 ""];

var btn1Path = [2, 
										4, 94, 
										38, 13, 
										10, 10,
										11, 94,
										11, 94,
										9, 19,
										23, 94,
										17, 94,
										26, 27,
										33, 36,
										0, 24,
										25, 94,
										0, 28,
										29, 94,
										26, 32,
										35, 94,
										0, 94,
										37, 94,
										48, 40,
										69, 45, 
										43, 45,
										0, 46,
										0, 46,
										52, 54,
										51, 94,
										53, 35,
										51, 33,
										0, 61,
										64, 65,
										0, 66,
										67, 67,
										0, 64,
										68, 94,
										0, 81,
										73, 72,
										0, 74,
										75, 80,
										0, 68,
										79, 94,
										76, 88,
										85, 87,
										0, 86,
										0, 84,
										89, 91,
										0, 92,
										93, 94,
										0];

var btn2Path = [4, 
										3, null, 
										5, 6, 
										7, 8, 
										9, null,
										12, null,
										11, 14,
										15, null,
										26, null,
										17,  20,
										21, 22,
										null, 30,
										26, null,
										null, 31,
										33, null,
										19, 34,
										34, null,
										null, null,
										33, null,
										39, 57,
										41, 42,
										44, 44,
										null, 47,
										null, 44,
										49, 50,
										54, null,
										55, 56,
										35, 35,
										null, 58,
										59, 60,
										null, 62,
										63, 64,
										null, 60,
										62, null,
										null, 70,
										71, 67,
										null, 77,
										79, 76,
										null, 78,
										79, null,
										79, 82,
										83, 84,
										null, 87,
										null, null,
										68, 90,
										null, 90,
										null, null,
										null];

var btn3Path = [btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, 18,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										33, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath, btn3EndPath,
										btn3EndPath];

var btn4Path = [btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, 16,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath, btn4EndPath,
										btn4EndPath];
var xpos = [3000,
			4500, 3500,
			2990, 990,
			-1010, -1010,
			-1010, -1010,
			490, 490,
			490, 990,
			-1010, -1010,
			2990, 4490,
			4490, 5990,
			5990, 4490,
			4490, -1010,
			490, 490,
			490, 7490,
			8990, 10490,
			-1010, 7490,
			8990, 8990,
			7490, 11990,
			8990, 10490,
			4490, 5990,
			5990, 4490,
			2660, 830,
			-1010, 830,
			2990, -1010,
			5990, 7490,
			8990, 11990,
			7490, 8990,
			8990, 11990,
			13490, 5990,
			5490, 5490,
			5490, 7490,
			7740, 7740,
			6590, 6590,
			8990, 10490,
			11990, 7490,
			6590, 6590,
			7740, 7740,
			8990, 10490, 
			10490, 8990,
			8990, 10490,
			11990, 9740,
			15990, 12990,
			14490, 15990, 
			15990, 14490,
			15990, 14490,
			14490, 15990,
			15990, 14490,
			17000];

var ypos = [1500,
			2200, 2850,
			3700, 3700,
			3700, 2200,
			700, -800,
			3000, 94,
			1500, 6700,
			6700, 5200,
			8200, 9700,
			8200, 8200,
			6700, 6700,
			5200, 8200,
			9700, 8200,
			11200, 8200,
			8200, 8200,
			11200, 9700,
			9700, 6700,
			11200, 6700, 
			5200, 6700,
			3700, 2200,
			-5300, -5300,
			-5300, -5300,
			-5300, -3800,
			-3800, -3800,
			3700, 2200,
			700, -800,
			3700, 3700,
			2200, 5200,
			6700, 700,
			-800, -2300,
			-3500, 700,
			-800, -2300,
			-800, -2300,
			-800, -800,
			-2300, -5300,
			-4400, -3400,
			-3500, -4400,
			-4400, -4400,
			-1400, -3400,
			-2300, -2400,
			-4400, -5300,
			8200, 10200, 
			8200, 10200, 
			11200, 11200,
			-5300, 700,
			2200, 2200,
			6700, 6700,
			17000];

var cards = [];

for(var i = 0; i < questions.length; i++){
	var card = new Card(questions[i], statements[i], btnTxt1[i], btnTxt2[i], btnTxt3[i], btnTxt4[i], btn1Path[i], btn2Path[i], btn3Path[i], btn4Path[i], xpos[i], ypos[i], 94);
	cards.push(card);
}

var svgX = [0, -3000];

var noPath = undefined;


var path1MX = [900, 620,
			   895, 900,
			   900, 900,
			   350, 350,
			   350, 900,
			   98, 900,
			   noPath, 625,
			   150, 620,
			   noPath, 150,
			   900, 900,
			   900, 320,
			   620, 75,
			   800, 900,
			   75, 900,
			   noPath, 900,
			   75, 75,
			   450, 900,
			   190, 100,
			   noPath, 900,
			   noPath, 900,
			   900, 900,
			   620, 900,
			   900, 450,
			   620, 900,
			   900, 120,
			   noPath, 900,
			   noPath, noPath,
			   120, noPath,
			   900, 900,
			   900, 450,
			   noPath, 620,
			   620, noPath,
			   620, noPath,
			   noPath, noPath,
			   900, 75,
			   900, noPath,
			   900, 900,
			   900, noPath,
			   75, 900,
			   noPath, noPath,
			   900, 620,
			   75, noPath,
			   620, noPath,
			   noPath, noPath,
			   75, 900,
			   620, noPath,
			   900];

var path1MY = [245, 495,
			   237, 245,
			   245, 245,
			   495, 495,
			   485, 245,
			   485, 245,
			   noPath, 495,
			   485, 495,
			   noPath, 495,
			   245, 245,
			   245, 485,
			   495, 495,
			   485, 240,
			   495, 245,
			   noPath, 245,
			   495, 495,
			   485, 150,
			   485, 495,
			   noPath, 245,
			   noPath, 245,
			   245, 245,
			   495, 245,
			   245, 485,
			   495, 245,
			   245, 495,
			   noPath, 245,
			   noPath, noPath,
			   495, noPath,
			   245, 245,
			   245, 850,
			   noPath, 495,
			   495, noPath,
			   495, noPath,
			   noPath, noPath,
			   245, 495,
			   225, noPath,
			   245, 245,
			   245, noPath,
			   495, 225,
			   noPath, noPath,
			   245, 495,
			   495, noPath,
			   495, noPath,
			   noPath,noPath,
			   495, 245,
			   495, noPath,
			   245];

var path1V = [455, 800,
			  94, 94,
			  94, 94,
			  1005, 1005,
			  1010, 94,
			  300, 94,
			  noPath, 1005,
			  1010, 1250,
			  noPath, 1010,
			  94, 94,
			  94, 1010,
			  1250, 1010,
			  1010, 94,
			  1005, 94,
			  noPath, 94,
			  1010, 1150,
			  1010, 94,
			  2770, 1010,
			  noPath, 94,
			  noPath, 94,
			  94, 94,
			  1005, 94,
			  94, 210,
			  200, 94,
			  94, 1005,
			  noPath, 94,
			  noPath, noPath,
			  1010, noPath,
			  94, 94,
			  94, 345,
			  noPath, 400,
			  600, noPath,
			  1010, noPath,
			  noPath, noPath,
			  94, 505,
			  94, noPath,
			  94, 94,
			  94, noPath,
			  605, 94,
			  noPath, noPath,
			  94, 1505,
			  200, noPath,
			  510, noPath,
			  noPath, noPath,
			  1010, 94,
			  4005, noPath,
			  94];

var path1H = [1000, -10000,
			  200, 600,
			  1100, 1100,
			  94, 94,
			  94, 200,
			  94, 112,
			  noPath, 94,
			  94, 880,
			  noPath, 94,
			  600, 2100,
			  600, 94,
			  880, 94,
			  94, 4800,
			  94, 600,
			  noPath, 600,
			  94, 94,
			  94, 700,
			  94, 94,
			  noPath, 600,
			  noPath, 600,
			  600, 930,
			  94, 940,
			  1260, 94,
			  3840, 600,
			  600, 94,
			  noPath, 600,
			  noPath, noPath,
			  94, noPath,
			  600, 200,
			  200, 750,
			  noPath, 2400,
			  2000, noPath,
			  94, noPath,
			  noPath, noPath,
			  1350, 94,
			  250, noPath,
			  350, 600,
			  600, noPath,
			  94, 600,
			  noPath, noPath,
			  5350, 94, 
			  1000, noPath,
			  94, noPath,
			  noPath, noPath,
			  94, 600,
			  94, noPath,
			  600];

var path1V1st = [false, true,
				 false, false,
				 false, false,
				 true, true,
				 true, false,
				 true, false,
				 noPath, true,
				 true, true,
				 noPath, true,
				 false, false,
				 false, true,
				 true, true,
				 true, false,
				 true, false,
				 noPath, false,
				 true, true,
				 true, false,
				 false, true,
				 noPath, false,
				 noPath, false,
				 false, false,
				 true, false,
				 false, true,
				 true, false,
				 false, true,
				 noPath, false,
				 noPath, noPath,
				 true, noPath,
				 false, true,
				 false, false,
				 noPath, true,
				 true, noPath,
				 true, noPath,
				 noPath, noPath,
				 false, true,
				 false, noPath,
				 false, false,
				 false, noPath,
				 true, false,
				 noPath, noPath,
				 false, false,
				 true, noPath,
				 true, noPath,
				 noPath, noPath,
				 true, false,
				 true, noPath,
				 false];

var path2MX = [150, 100,
               noPath, noPath,
               620, noPath,
               620, 900,
               noPath, noPath,
               270, 300,
               noPath, 900,
               noPath, 150,
               noPath, 900,
               noPath, noPath,
               noPath, noPath,
               70, noPath,
               noPath, 100,
               900, noPath,
               noPath, 100,
               900, 900,
               noPath, noPath,
               noPath, 900,
               noPath, noPath,
               noPath, noPath,
               620, noPath,
               620, 75,
               noPath, noPath,
               900, noPath,
               noPath, noPath,
               noPath, noPath,
               noPath, noPath,
               noPath, noPath,
               450, noPath,
               noPath, noPath,
               noPath, 3020,
               2620, noPath,
               noPath, noPath,
               noPath, noPath,
               noPath, 900,
               noPath, noPath,
               noPath, noPath,
               noPath, noPath,
               900, noPath,
               noPath, noPath,
               noPath, noPath,
               noPath, noPath,
               noPath, noPath,
               noPath, noPath,
               900, noPath,
               noPath, noPath,
               noPath];

var path2MY = [495, 495,
			   noPath, noPath,
			   495, noPath,
			   1500, 245,
			   noPath, noPath,
			   485, 495,
			   noPath, 245,
			   noPath, 495,
			   noPath, 245,
			   noPath, noPath,
			   noPath, noPath,
			   495, noPath,
			   noPath, 695,
			   245, noPath,
			   noPath, 495,
			   245, 245,
			   noPath, noPath,
			   noPath, 245,
			   noPath, noPath,
			   noPath, noPath,
			   495, noPath,
			   695, 485,
			   noPath, noPath,
			   245, noPath,
			   noPath, noPath,
			   noPath,noPath,
			   noPath, noPath,
			   noPath, noPath,
			   495, noPath,
			   noPath, noPath,
			   noPath, 895,
			   1095, noPath,
			   noPath, noPath,
			   noPath, noPath,
			   noPath, 245,
			   noPath, noPath,
			   noPath, noPath,
			   noPath, noPath,
			   245, noPath,
			   noPath, noPath,
			   noPath, noPath,
			   noPath, noPath,
			   noPath, noPath,
			   noPath, noPath,
			   245, noPath,
			   noPath, noPath,
			   noPath];

var path2V = [1705, 400,
			  noPath, noPath,
			  2505, noPath,
			  -500, -500,
			  noPath, noPath,
			  1010, 1005,
			  noPath, 94,
			  noPath, 2750,
			  noPath, 3000,
			  noPath, noPath,
			  noPath, noPath,
			  2505, noPath,
			  noPath, 94,
			  94, noPath,
			  noPath, 200,
			  94, 94,
			  noPath, noPath,
			  noPath, 1260,
			  noPath, noPath,
			  noPath, noPath,
			  210, noPath,
			  94, 1010,
			  noPath, noPath,
			  94, noPath,
			  noPath, noPath,
			  noPath, noPath,
			  noPath, noPath,
			  noPath, noPath,
			  1005, noPath,
			  noPath, noPath,
			  noPath, -405,
			  1300, noPath,
			  noPath, noPath,
			  noPath, noPath,
			  noPath, 94,
			  noPath, noPath,
			  noPath, noPath,
			  noPath, noPath,
			  860, noPath,
			  noPath,noPath,
			  noPath, noPath,
			  noPath,noPath,
			  noPath, noPath,
			  noPath, noPath,
			  1255, noPath,
			  noPath, noPath,
			  noPath];

var path2H = [0, -200,
			  noPath, noPath,
			  94, noPath,
			  880, 700,
			  noPath, noPath,
			  94, 94,
			  noPath, 1100,
			  noPath, 94,
			  noPath, 100,
			  noPath, noPath,
			  noPath, noPath,
			  94, noPath,
			  noPath, 5000,
			  600, noPath,
			  noPath, 5000,
			  600, 2300,
			  noPath, noPath,
			  noPath, 1000,
			  noPath, noPath,
			  noPath, noPath,
			  94, noPath,
			  3650, 94,
			  noPath, noPath,
			  940, noPath,
			  noPath, noPath,
			  noPath, noPath,
			  noPath, noPath,
			  noPath, noPath,
			  94, noPath,
			  noPath, noPath,
			  noPath, 94,
			  94, noPath,
			  noPath, noPath,
			  noPath, noPath,
			  noPath, 250,
			  noPath, noPath,
			  noPath, noPath,
			  noPath, noPath,
			  2400, noPath,
			  noPath, noPath,
			  noPath, noPath,
			  noPath,noPath,
			  noPath, noPath,
			  noPath, noPath,
			  1000, noPath,
			  noPath, noPath,
			  noPath];

var path2V1st = [true, true,
				 noPath, noPath,
				 true, noPath,
				 true, false,
				 noPath, noPath,
				 true, true,
				 noPath, false,
				 noPath, true,
				 noPath, false,
				 noPath, noPath,
				 noPath, noPath,
				 true, noPath,
				 noPath, noPath,
				 false, noPath,
				 noPath, true,
				 false, false,
				 noPath, noPath,
				 noPath, false,
				 noPath, noPath,
				 noPath, noPath,
				 true, noPath,
				 false, true,
				 noPath, noPath,
				 false, noPath,
				 noPath, noPath,
				 noPath, noPath,
				 noPath, noPath,
				 noPath, noPath,
				 true, noPath,
				 noPath, noPath,
				 noPath, true,
				 true, noPath,
				 noPath, noPath,
				 noPath, noPath,
				 noPath, false,
				 noPath, noPath,
				 noPath, noPath,
				 noPath, noPath,
				 false, noPath,
				 noPath, noPath,
				 noPath, noPath,
				 noPath, noPath,
				 noPath, noPath,
				 noPath, noPath,
				 false, noPath,
				 noPath, noPath,
				 noPath];


				 